1 партия изменений.html
Fraico/Training-project-Calendar- pull request #1
Opened 2019-04-08 06:45 UTC by Fraico

2019-04-08 08:43 UTC, polyakovin requested changes

2019-04-08 08:43 UTC, polyakovin commented on index.html
> +	<meta name="description" content="calendar project">
Почему тут решил по-английски написать? :)

2019-04-08 08:43 UTC, polyakovin commented on index.html
>  	<meta charset="UTF-8">
Отступы так и не поправил. Сегодня вечером посмотрим.

2019-04-08 08:51 UTC, Fraico commented on index.html
> +	<meta name="description" content="calendar project">
Ну, это такой небольшой посыл для себя в  сторону углублений знаний английского и в сторону его использования))

2019-04-09 20:14 UTC, polyakovin requested changes

2019-04-09 20:14 UTC, polyakovin commented on index.html
> +        <p>Текущее время 12:30</p>
Это не абзац

2019-04-09 20:14 UTC, polyakovin commented on index.html
> +        <ul>
зачем тут отступ?

2019-04-09 20:14 UTC, polyakovin commented on index.html
> +      <div>
Зачем этот div?

2019-04-09 20:14 UTC, polyakovin commented on index.html
> +    </div>
Зачем следующие 3 отступа сместил?

2019-04-09 20:14 UTC, polyakovin commented on index.html
>  <html>
Почему не закрыл тег? И где doctype?

2019-05-06 12:20 UTC, closed without merging